import {
  RiRocketFill,
  RiLightbulbFill,
  RiCodeBoxFill,
  RiDashboardFill,
  RiPuzzleFill,
  RiBrainFill,
  RiFlashlightFill,
  RiCompassFill,
  RiLeafFill,
  RiFireFill,
  RiThunderstormsFill,
  RiMagicFill,
  RiSparklingFill,
  RiFolderFill,
  RiPlanetFill,
  RiMeteorFill,
  RiCactusFill,
  RiFlowerFill,
  RiCupFill,
  RiAnchorFill,
  RiStarFill,
  RiHeartFill,
  RiTrophyFill,
  RiShieldFill,
  RiTargetFill,
  RiBugFill,
  RiPaletteFill,
  RiCameraFill,
  RiBookFill,
  RiGamepadFill,
  RiShoppingCartFill,
  RiSmartphoneFill,
  RiTvFill,
  RiMusicFill,
  RiGiftFill,
  RiMailFill,
  RiBellFill,
  RiTimeFill,
  RiHomeFill,
  RiMapPinFill,
} from '@remixicon/react'

export const iconOptions = [
  { name: 'RiFolderFill', component: RiFolderFill, label: 'Folder' },
  { name: 'RiRocketFill', component: RiRocketFill, label: 'Rocket' },
  { name: 'RiLightbulbFill', component: RiLightbulbFill, label: 'Lightbulb' },
  { name: 'RiCodeBoxFill', component: RiCodeBoxFill, label: 'Code Box' },
  { name: 'RiDashboardFill', component: RiDashboardFill, label: 'Dashboard' },
  { name: 'RiPuzzleFill', component: RiPuzzleFill, label: 'Puzzle' },
  { name: 'RiBrainFill', component: RiBrainFill, label: 'Brain' },
  { name: 'RiFlashlightFill', component: RiFlashlightFill, label: 'Flashlight' },
  { name: 'RiCompassFill', component: RiCompassFill, label: 'Compass' },
  { name: 'RiLeafFill', component: RiLeafFill, label: 'Leaf' },
  { name: 'RiFireFill', component: RiFireFill, label: 'Fire' },
  { name: 'RiThunderstormsFill', component: RiThunderstormsFill, label: 'Storm' },
  { name: 'RiMagicFill', component: RiMagicFill, label: 'Magic' },
  { name: 'RiSparklingFill', component: RiSparklingFill, label: 'Sparkle' },
  { name: 'RiPlanetFill', component: RiPlanetFill, label: 'Planet' },
  { name: 'RiMeteorFill', component: RiMeteorFill, label: 'Meteor' },
  { name: 'RiCactusFill', component: RiCactusFill, label: 'Cactus' },
  { name: 'RiFlowerFill', component: RiFlowerFill, label: 'Flower' },
  { name: 'RiCupFill', component: RiCupFill, label: 'Cup' },
  { name: 'RiAnchorFill', component: RiAnchorFill, label: 'Anchor' },
  { name: 'RiStarFill', component: RiStarFill, label: 'Star' },
  { name: 'RiHeartFill', component: RiHeartFill, label: 'Heart' },
  { name: 'RiTrophyFill', component: RiTrophyFill, label: 'Trophy' },
  { name: 'RiShieldFill', component: RiShieldFill, label: 'Shield' },
  { name: 'RiTargetFill', component: RiTargetFill, label: 'Target' },
  { name: 'RiBugFill', component: RiBugFill, label: 'Bug' },
  { name: 'RiPaletteFill', component: RiPaletteFill, label: 'Palette' },
  { name: 'RiCameraFill', component: RiCameraFill, label: 'Camera' },
  { name: 'RiBookFill', component: RiBookFill, label: 'Book' },
  { name: 'RiGamepadFill', component: RiGamepadFill, label: 'Game' },
  { name: 'RiShoppingCartFill', component: RiShoppingCartFill, label: 'Cart' },
  { name: 'RiSmartphoneFill', component: RiSmartphoneFill, label: 'Mobile' },
  { name: 'RiTvFill', component: RiTvFill, label: 'TV' },
  { name: 'RiMusicFill', component: RiMusicFill, label: 'Music' },
  { name: 'RiGiftFill', component: RiGiftFill, label: 'Gift' },
  { name: 'RiMailFill', component: RiMailFill, label: 'Mail' },
  { name: 'RiBellFill', component: RiBellFill, label: 'Bell' },
  { name: 'RiTimeFill', component: RiTimeFill, label: 'Time' },
  { name: 'RiHomeFill', component: RiHomeFill, label: 'Home' },
  { name: 'RiMapPinFill', component: RiMapPinFill, label: 'Location' }
] as const

export type IconName = typeof iconOptions[number]['name']

export function getIconComponent(name: string) {
  return iconOptions.find(opt => opt.name === name)?.component || RiFolderFill
}
