import "@testing-library/jest-dom/vitest"

// Set up test environment variables
process.env.NODE_ENV = "test"
process.env.NEXT_PUBLIC_APP_URL = "http://localhost:3000"
process.env.NEXT_PUBLIC_API_URL = "http://localhost:3000/api"
process.env.DATABASE_URL = "postgresql://test:test@localhost:5432/test"
process.env.SUPABASE_URL = "https://test.supabase.co"
process.env.SUPABASE_ANON_KEY = "test-anon-key"
process.env.SUPABASE_SERVICE_ROLE_KEY = "test-service-role-key"
process.env.R2_ACCOUNT_ID = "test-account-id"
process.env.R2_ACCESS_KEY_ID = "test-access-key"
process.env.R2_SECRET_ACCESS_KEY = "test-secret-key"
process.env.R2_BUCKET_NAME = "test-bucket"
process.env.R2_PUBLIC_URL = "https://test.r2.dev"
process.env.GOOGLE_CLIENT_ID = "test-client-id"
process.env.GOOGLE_CLIENT_SECRET = "test-client-secret"
process.env.GOOGLE_REDIRECT_URI = "http://localhost:3000/api/auth/callback/google"
process.env.BETTER_AUTH_SECRET = "test-secret-key-with-at-least-32-characters"
process.env.BETTER_AUTH_URL = "http://localhost:3000"
