/**
 * Helpers for generating a compose.override.yml file that publishes app ports
 * to the host. This file is only written when the user selects "standalone"
 * deployment mode (no reverse proxy) during `ui-syncup init`.
 *
 * Docker Compose automatically merges compose.override.yml with compose.yml
 * when BOTH files are passed via `-f`. We keep compose.yml clean so it works
 * safely on PaaS platforms (Dokploy, Coolify) out of the box.
 */

/**
 * Returns the content for a compose.override.yml that publishes the app port
 * to the host machine, enabling direct IP access (e.g. http://server:3000).
 */
export function buildStandaloneOverride(port: string): string {
  return [
    '# Auto-generated by ui-syncup init — standalone deployment mode.',
    '# Publishes the app port to the host for direct IP/domain access.',
    '# Remove this file (or re-run `ui-syncup init`) if you switch to a',
    '# reverse proxy (Dokploy / Coolify / Traefik / Caddy).',
    'services:',
    '  app:',
    '    ports:',
    `      - "\${PORT:-${port}}:\${PORT:-${port}}"`,
    '',
  ].join('\n')
}
