import { pgTable, timestamp, varchar, text } from "drizzle-orm/pg-core";

/**
 * Storage for better-auth verification payloads (state, tokens, etc.)
 *
 * Schema follows the structure expected by better-auth:
 * - id: generated by better-auth as alphanumeric string
 * - identifier: lookup key (state string)
 * - value: serialized payload (JSON string)
 * - expiresAt: expiration timestamp
 * - createdAt / updatedAt: auditing fields
 */
export const betterAuthVerifications = pgTable("better_auth_verifications", {
  id: text("id").primaryKey(),
  identifier: varchar("identifier", { length: 255 }).notNull().unique(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
