import type { AttachmentAnnotation, AnnotationAuthor } from '../types';

export interface LabelValidationResult {
  isValid: boolean;
  error?: string;
}

const MAX_LABEL_LENGTH = 10;
const LABEL_PATTERN = /^[a-zA-Z0-9]+$/;

/**
 * Validates an annotation label for editing or creation.
 *
 * Checks:
 * - Not empty
 * - Within max length (10 characters)
 * - Alphanumeric only
 * - Unique among annotations (excluding current annotation)
 *
 * @param label - Label to validate
 * @param annotations - All existing annotations
 * @param currentAnnotationId - ID of annotation being edited (optional, for uniqueness check)
 * @returns Validation result with error message if invalid
 *
 * @example
 * ```ts
 * validateAnnotationLabel('1', annotations) // { isValid: false, error: 'Label already exists' }
 * validateAnnotationLabel('4', annotations) // { isValid: true }
 * validateAnnotationLabel('', annotations) // { isValid: false, error: 'Label cannot be empty' }
 * ```
 */
export function validateAnnotationLabel<A extends AnnotationAuthor = AnnotationAuthor>(
  label: string,
  annotations: AttachmentAnnotation<A>[],
  currentAnnotationId?: string
): LabelValidationResult {
  // Check if empty
  const trimmed = label.trim();
  if (!trimmed) {
    return {
      isValid: false,
      error: 'Label cannot be empty',
    };
  }

  // Check length
  if (trimmed.length > MAX_LABEL_LENGTH) {
    return {
      isValid: false,
      error: `Label cannot exceed ${MAX_LABEL_LENGTH} characters`,
    };
  }

  // Check format (alphanumeric only)
  if (!LABEL_PATTERN.test(trimmed)) {
    return {
      isValid: false,
      error: 'Label must contain only letters and numbers',
    };
  }

  // Check uniqueness (case-insensitive)
  const normalizedLabel = trimmed.toLowerCase();
  const isDuplicate = annotations.some(
    (annotation) =>
      annotation.id !== currentAnnotationId &&
      annotation.label.toLowerCase() === normalizedLabel
  );

  if (isDuplicate) {
    return {
      isValid: false,
      error: 'Label already exists',
    };
  }

  return { isValid: true };
}

/**
 * Validates annotation description.
 *
 * @param description - Description to validate
 * @param maxLength - Maximum allowed length (default: 500)
 * @returns Validation result
 */
export function validateAnnotationDescription(
  description: string,
  maxLength: number = 500
): LabelValidationResult {
  const trimmed = description.trim();

  if (trimmed.length > maxLength) {
    return {
      isValid: false,
      error: `Description cannot exceed ${maxLength} characters`,
    };
  }

  return { isValid: true };
}

/**
 * Checks if a label is auto-generated (numeric sequential).
 *
 * @param label - Label to check
 * @returns True if label is a positive integer
 *
 * @example
 * ```ts
 * isAutoGeneratedLabel('1') // true
 * isAutoGeneratedLabel('42') // true
 * isAutoGeneratedLabel('A') // false
 * isAutoGeneratedLabel('1a') // false
 * ```
 */
export function isAutoGeneratedLabel(label: string): boolean {
  const num = parseInt(label, 10);
  return !isNaN(num) && num > 0 && String(num) === label;
}
